apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-7lox
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhfk-tenant/rhtap-demo-app/hacbs-test-project-7lox@sha256:dd18c7f772862da35e783e4a78356e950e0a8a4a0aeac28bd488af15c6a46b56
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
