apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-7lox
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-7lox
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-7lox
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-7lox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-7lox
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-lhfk-tenant/rhtap-demo-app/hacbs-test-project-7lox@sha256:4a2757d8cb77fa3306078be6f7851b4dfa1999d99f2ea7e08bc6970a3079f6a3
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
